#!/usr/bin/env python3
"""
Apollo配置同步脚本
从Apollo配置中心拉取配置并生成.env文件
"""

import os
import sys
import json
import argparse
import logging
from pathlib import Path
from datetime import datetime

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


class ApolloConfigSync:
    def __init__(
        self,
        apollo_url: str = "",
        app_id: str = "",
        cluster: str = "default",
        namespace: str = "application",
        output_dir: str = "."
    ):
        self.apollo_url = apollo_url.rstrip("/")
        self.app_id = app_id
        self.cluster = cluster
        self.namespace = namespace
        self.output_dir = Path(output_dir)

    def fetch_config(self) -> dict:
        if not self.apollo_url or not self.app_id:
            logger.warning("Apollo not configured, using default config")
            return {}

        try:
            import httpx
            url = f"{self.apollo_url}/configs/{self.app_id}/{self.cluster}/{self.namespace}"
            logger.info(f"Fetching config from: {url}")

            with httpx.Client(timeout=30) as client:
                response = client.get(url)
                response.raise_for_status()

                data = response.json()
                configurations = data.get("configurations", {})

                logger.info(f"Fetched {len(configurations)} configurations")
                return configurations

        except ImportError:
            logger.warning("httpx not installed, using default config")
            return {}
        except Exception as e:
            logger.error(f"Failed to fetch config: {e}")
            return {}

    def generate_env_file(self, configurations: dict):
        env_file = self.output_dir / ".env"
        backup_file = None

        if env_file.exists():
            backup_file = self.output_dir / f".env.backup.{datetime.now().strftime('%Y%m%d%H%M%S')}"
            env_file.rename(backup_file)
            logger.info(f"Backed up existing .env to {backup_file}")

        sensitive_keys = {
            "JWT_SECRET", "DB_PASSWORD", "REDIS_PASSWORD",
            "DEEPSEEK_API_KEY", "KIMI_API_KEY", "OPENAI_API_KEY",
            "QDRANT_API_KEY", "SENTRY_DSN"
        }

        with open(env_file, "w", encoding="utf-8") as f:
            f.write(f"# Auto-generated by sync_config.py at {datetime.now().isoformat()}\n")
            f.write(f"# Apollo App: {self.app_id}\n\n")

            for key, value in sorted(configurations.items()):
                if key in sensitive_keys:
                    value = self._mask_sensitive(value)

                if isinstance(value, bool):
                    value = "true" if value else "false"
                elif isinstance(value, (dict, list)):
                    value = json.dumps(value)

                f.write(f"{key}={value}\n")

        logger.info(f"Generated {env_file}")

        if backup_file:
            logger.info(f"Backup available at: {backup_file}")

        return env_file

    def _mask_sensitive(self, value: str) -> str:
        if not value:
            return value
        if len(value) <= 8:
            return "***"
        return value[:4] + "***" + value[-4:]

    def validate_config(self, configurations: dict) -> list:
        errors = []

        required_keys = [
            "APP_NAME",
            "JWT_SECRET",
            "DEEPSEEK_API_KEY",
            "KIMI_API_KEY"
        ]

        missing_keys = [key for key in required_keys if key not in configurations]
        if missing_keys:
            errors.append(f"Missing required keys: {', '.join(missing_keys)}")

        if "JWT_SECRET" in configurations:
            secret = configurations["JWT_SECRET"]
            if len(secret) < 32:
                errors.append("JWT_SECRET should be at least 32 characters")

        return errors

    def sync(self) -> bool:
        logger.info("Starting Apollo config sync...")

        configurations = self.fetch_config()

        if not configurations:
            logger.warning("No configurations fetched, checking for existing .env")
            env_file = self.output_dir / ".env"
            if env_file.exists():
                logger.info("Using existing .env file")
                return True
            else:
                logger.error("No configurations available")
                return False

        errors = self.validate_config(configurations)
        if errors:
            for error in errors:
                logger.warning(f"Validation: {error}")

        env_file = self.generate_env_file(configurations)

        logger.info(f"Config sync completed successfully!")
        logger.info(f"Output: {env_file}")

        return True


def main():
    parser = argparse.ArgumentParser(description="Sync Apollo config to .env")
    parser.add_argument("--apollo-url", "-u", default=os.getenv("APOLLO_URL", ""), help="Apollo URL")
    parser.add_argument("--app-id", "-a", default=os.getenv("APOLLO_APP_ID", ""), help="Apollo App ID")
    parser.add_argument("--cluster", "-c", default=os.getenv("APOLLO_CLUSTER", "default"), help="Apollo Cluster")
    parser.add_argument("--namespace", "-n", default="application", help="Apollo Namespace")
    parser.add_argument("--output-dir", "-o", default=".", help="Output directory for .env")
    parser.add_argument("--dry-run", action="store_true", help="Dry run mode")

    args = parser.parse_args()

    sync = ApolloConfigSync(
        apollo_url=args.apollo_url,
        app_id=args.app_id,
        cluster=args.cluster,
        namespace=args.namespace,
        output_dir=args.output_dir
    )

    if args.dry_run:
        logger.info("Dry run mode - fetching config only")
        config = sync.fetch_config()
        print(json.dumps(config, indent=2, ensure_ascii=False))
        return 0

    success = sync.sync()
    return 0 if success else 1


if __name__ == "__main__":
    sys.exit(main())
